# Generated by Django 5.2.1 on 2025-06-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_file_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hook_test",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
