# Generated by Django 5.2.1 on 2025-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_hook_test"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="hook_test",
            new_name="hook",
        ),
    ]
